import { KHQR, CURRENCY, TAG, QRPayload } from '../index';

const expirationTimestamp = Date.now() + 1 * 60 * 1000;

const amountTestData: { statement: string; data: QRPayload; result: string }[] = [
    {
        statement: 'Amount test 1',
        data: {
            tag: TAG.INDIVIDUAL,
            accountID: 'jonhsmith@nbcq',
            merchantName: 'Jonh Smith',
            merchantCity: 'Siem Reap',
            currency: CURRENCY.KHR,
            amount: 100.0,
            acquiringBank: 'Dev Bank',
            additionalData: {
                mobileNumber: '85512345678',
                billNumber: 'INV-2021-07-65822',
                storeLabel: 'BKK-1',
                terminalLabel: '012345',
            },
            merchantID: '012345678',
            expirationTimestamp,
        },
        result: '100',
    },
    {
        statement: 'Amount test 2',
        data: {
            tag: TAG.INDIVIDUAL,
            accountID: 'jonhsmith@nbcq',
            merchantName: 'Jonh Smith',
            merchantCity: 'Siem Reap',
            currency: CURRENCY.KHR,
            amount: 100.0,
            acquiringBank: 'Dev Bank',
            additionalData: {
                mobileNumber: '85512345678',
                billNumber: 'INV-2021-07-65822',
                storeLabel: 'BKK-1',
                terminalLabel: '012345',
            },
            merchantID: '012345678',
            expirationTimestamp,
        },
        result: '100',
    },
    {
        statement: 'Amount test 3',
        data: {
            tag: TAG.INDIVIDUAL,
            accountID: 'jonhsmith@nbcq',
            merchantName: 'Jonh Smith',
            merchantCity: 'Siem Reap',
            currency: CURRENCY.KHR,
            amount: 100.0,
            acquiringBank: 'Dev Bank',
            additionalData: {
                mobileNumber: '85512345678',
                billNumber: 'INV-2021-07-65822',
                storeLabel: 'BKK-1',
                terminalLabel: '012345',
            },
            merchantID: '012345678',
            expirationTimestamp,
        },
        result: '100',
    },
    {
        statement: 'Amount test 4',
        data: {
            tag: TAG.INDIVIDUAL,
            accountID: 'jonhsmith@nbcq',
            merchantName: 'Jonh Smith',
            merchantCity: 'Siem Reap',
            currency: CURRENCY.KHR,
            amount: 9999999999.0,
            acquiringBank: 'Dev Bank',
            additionalData: {
                mobileNumber: '85512345678',
                billNumber: 'INV-2021-07-65822',
                storeLabel: 'BKK-1',
                terminalLabel: '012345',
            },
            merchantID: '012345678',
            expirationTimestamp,
        },
        result: '9999999999',
    },
    {
        statement: 'Amount test 5',
        data: {
            tag: TAG.INDIVIDUAL,
            accountID: 'jonhsmith@nbcq',
            merchantName: 'Jonh Smith',
            merchantCity: 'Siem Reap',
            currency: CURRENCY.KHR,
            amount: 10000,
            acquiringBank: 'Dev Bank',
            additionalData: {
                mobileNumber: '85512345678',
                billNumber: 'INV-2021-07-65822',
                storeLabel: 'BKK-1',
                terminalLabel: '012345',
            },
            merchantID: '012345678',
            expirationTimestamp,
        },
        result: '10000',
    },
    {
        statement: 'Amount test 6',
        data: {
            tag: TAG.INDIVIDUAL,
            accountID: 'jonhsmith@nbcq',
            merchantName: 'Jonh Smith',
            merchantCity: 'Siem Reap',
            currency: CURRENCY.USD,
            amount: 1.12,
            acquiringBank: 'Dev Bank',
            additionalData: {
                mobileNumber: '85512345678',
                billNumber: 'INV-2021-07-65822',
                storeLabel: 'BKK-1',
                terminalLabel: '012345',
            },
            merchantID: '012345678',
            expirationTimestamp,
        },
        result: '1.12',
    },
    {
        statement: 'Amount test 7',
        data: {
            tag: TAG.INDIVIDUAL,
            accountID: 'jonhsmith@nbcq',
            merchantName: 'Jonh Smith',
            merchantCity: 'Siem Reap',
            currency: CURRENCY.USD,
            amount: 1000,
            acquiringBank: 'Dev Bank',
            additionalData: {
                mobileNumber: '85512345678',
                billNumber: 'INV-2021-07-65822',
                storeLabel: 'BKK-1',
                terminalLabel: '012345',
            },
            merchantID: '012345678',
            expirationTimestamp,
        },
        result: '1000',
    },
    {
        statement: 'Amount test 8',
        data: {
            tag: TAG.INDIVIDUAL,
            accountID: 'jonhsmith@nbcq',
            merchantName: 'Jonh Smith',
            merchantCity: 'Siem Reap',
            currency: CURRENCY.USD,
            amount: 100.11,
            acquiringBank: 'Dev Bank',
            additionalData: {
                mobileNumber: '85512345678',
                billNumber: 'INV-2021-07-65822',
                storeLabel: 'BKK-1',
                terminalLabel: '012345',
            },
            merchantID: '012345678',
            expirationTimestamp,
        },
        result: '100.11',
    },
    {
        statement: 'Amount test 9',
        data: {
            tag: TAG.INDIVIDUAL,
            accountID: 'jonhsmith@nbcq',
            merchantName: 'Jonh Smith',
            merchantCity: 'Siem Reap',
            currency: CURRENCY.USD,
            amount: 100.12,
            acquiringBank: 'Dev Bank',
            additionalData: {
                mobileNumber: '85512345678',
                billNumber: 'INV-2021-07-65822',
                storeLabel: 'BKK-1',
                terminalLabel: '012345',
            },
            merchantID: '012345678',
            expirationTimestamp,
        },
        result: '100.12',
    },
    {
        statement: 'Amount test 10',
        data: {
            tag: TAG.INDIVIDUAL,
            accountID: 'jonhsmith@nbcq',
            merchantName: 'Jonh Smith',
            merchantCity: 'Siem Reap',
            currency: CURRENCY.USD,
            amount: 12345678901.0,
            acquiringBank: 'Dev Bank',
            additionalData: {
                mobileNumber: '85512345678',
                billNumber: 'INV-2021-07-65822',
                storeLabel: 'BKK-1',
                terminalLabel: '012345',
            },
            merchantID: '012345678',
            expirationTimestamp,
        },
        result: '12345678901',
    },
    {
        statement: 'Amount test 11',
        data: {
            tag: TAG.INDIVIDUAL,
            accountID: 'jonhsmith@nbcq',
            merchantName: 'Jonh Smith',
            merchantCity: 'Siem Reap',
            currency: CURRENCY.USD,
            amount: 9999999999.99,
            acquiringBank: 'Dev Bank',
            merchantID: '012345678',
            additionalData: {
                mobileNumber: '85512345678',
                billNumber: 'INV-2021-07-65822',
                storeLabel: 'BKK-1',
                terminalLabel: '012345',
            },
            expirationTimestamp,
        },
        result: '9999999999.99',
    },
    {
        statement: 'Name in UTF-8',
        data: {
            tag: TAG.INDIVIDUAL,
            accountID: 'jonhsmith@nbcq',
            merchantName: 'ចន ស្មីន',
            merchantCity: 'Siem Reap',
            currency: CURRENCY.KHR,
            amount: 100.0,
            acquiringBank: 'Dev Bank',
            merchantID: '012345678',
            additionalData: {
                billNumber: 'INV-2021-07-65822',
                storeLabel: 'BKK-1',
                terminalLabel: '012345',
                mobileNumber: '85512345678',
            },
            expirationTimestamp,
        },
        result: '100',
    },
];

amountTestData.forEach((data) => {
    test(data.statement, () => {
        const res = KHQR.generate(data.data);
        const decodeValue = KHQR.parse(String(res.data?.qr));
        expect(decodeValue.data?.transactionAmount).toBe(data.result);
    });
});
